### ISSUE TITLE
Sublime Text 3 compatibility?

### ISSUE THREAD

**Issue by kbsali** [du-song/SublimeFormatSQL#11]
Hi,

i used to use this plugin a lot while on Sublime Text 2,
but after i recently upgraded to ST3, i'm all sad not to be able to use it anymore.
Any chance you could make it compatible with ST3?

Thx!

**Comment by arsham** [comment]
+1

**Comment by realholgi** [comment]
+1

**Comment by kgantsov** [comment]
I added ST3 supporting (https://github.com/freewizard/SublimeFormatSQL/pull/12) but @freewizard didn't update sublime package manager and you can't install it from sublime package manager.
But you can clone this repo to your ~/.config/sublime-text-3/Packages directory then reload ST3 and app will work.

**Comment by matpowel** [comment]
@freewizard can you please accept this PR? :) I really like the plugin but can't go back to ST2, ST3 is sweet.

**Comment by dmmalam** [comment]
+1

**Comment by mlegenhausen** [comment]
+1

**Comment by GordonWang** [comment]
+1
