### ISSUE TITLE
"Format SQL Statement" menu item is greyed out

### ISSUE THREAD

**Issue by ken-maestro** [du-song/SublimeFormatSQL#15]
I installed it on ST2 v2.0.2 build 2221 on OSX 10.8.5. But the menu item is greyed out. Any way I can debug this? Or do you have any idea what's wrong with it?

**Comment by akloeber** [comment]
Maybe this is is a duplicate of #14. Just restart ST2 to reload plugins and check for the error described there in console view.

**Comment by ken-maestro** [comment]
Oh yea i think this might be the same issue.
