### ISSUE TITLE
Submit plugin to Package Control

### ISSUE THREAD

**Issue by kbsali** [du-song/SublimeFormatSQL#5]
It would be so useful if you could create the approriate packages.json as describe here :
http://wbond.net/sublime_packages/package_control/package_developers#Submitting_a_Package
so your plugin is available for install through "package control"

Thanks!

**Comment by du-song** [comment]
hi, it's already in package control.

**Comment by kbsali** [comment]
damn you are right, sorry about that
I can see it here : http://wbond.net/sublime_packages/community
But not on sublime's side...?

**Comment by du-song** [comment]
you won't see it in "Install Package" command if it's already installed
(either from git or package control)

Regards,
Du Song

**Comment by kbsali** [comment]
... you are right! :| sorry! :)
